### ISSUE TITLE
Confirmation email on cancel

### ISSUE THREAD

**Issue by davidll** [Codeko/magento2-redsys#1]
Hello!
I am using Magento 2.1.8 with a custom theme (from luma) and your bundle (3.0.6) and I have detected that when canceling the order in the tpv the confirmation email is sent.
With paypal it doesn't happen.

**Comment by boris-burgos** [comment]
Hi!.
This is a issue related to Magento 2.1.8. The module has been tested until Magento 2.1.5 and Magento is making breaking changes in minor version updates.
In the next develop round we will test the module in the most recents Magento 2 version. Until that any help is appreciated.

**Comment by davidll** [comment]
Hi!
I can not find a solution... Doing tests I have seen that the mail is sent before redirecting to the tpv, not when canceling. I think the problem is that the order at that point is put in "Payment Review", it should be in "Processing"

**Comment by rafaelcalero** [comment]
@davidll **About the confirmation e-mail:** I don't see it as a module issue, it is developed with an order concept different from paypal. An order is when the customer confirms the order (does not mean that he has paid), in fact, the customer may have problems with his payment and then return to his account and try to pay. This, from my point of view, is correct. If you do not want the confirmation e-mail to arrive (without payment) you can disable it in: Sales -> Sales Email -> Order. After payment you will receive the invoice e-mail. Or you can customize both e-mails.
