### ISSUE TITLE
Payment review after complete payment. Magento 2.3

### ISSUE THREAD

**Issue by pabman11** [Codeko/magento2-redsys#10]
Hello! 

When a user pay, redsys don't change status to processing after complete or cancel the order. It set the payment_review status

In addition, the mail is sended after the creation of the order, and if Redsys fail or the user cancel this, the new order mail is sended, confusing the customer.

- [ ] Payment review status

- [ ] New order mail after order canceled

**Comment by boris-burgos** [comment]
Hi.
The first point is probably configuration/environment problem. 
About the second point Redsys module not send emails, only changes the normal Magento order status. So is not a module issue.
Regards.

**Comment by Eloy97** [comment]
> Hello!
> 
> When a user pay, redsys don't change status to processing after complete or cancel the order. It set the payment_review status
> 
> In addition, the mail is sended after the creation of the order, and if Redsys fail or the user cancel this, the new order mail is sended, confusing the customer.
> 
> * [ ]  Payment review status
> * [ ]  New order mail after order canceled



> Hi.
> The first point is probably configuration/environment problem.
> About the second point Redsys module not send emails, only changes the normal Magento order status. So is not a module issue.
> Regards.

Hola, yo tengo los mismos problemas que @pabman11 , ya sea cancelando el pedido o terminando el proceso de compra, el estado del pedido se queda en Payment Review, si se puede dar problema por la configuración de magento 2.3.3 o el servidor ¿puede decirme que podría ser para facilitar la búsqueda del problema?
