### ISSUE TITLE
El estado permanece en Payment Review despues de pagar

### ISSUE THREAD

**Issue by Julen10** [Codeko/magento2-redsys#11]
Despues de que alguien haga un pedido y lo pague o lo cancele, se ejecuta el controllador Notify pero no llega a actualizar el estado del mismo.

Debería actualizarse como puedo ver aqui https://github.com/Codeko/magento2-redsys/blob/31ccfbb13320a43ea55912134b9dcd8352581b62/Controller/Index/Notify.php#L131

**Comment by boris-burgos** [comment]
@Julen10 please write your issues in english, I will close this one.

If the order status is not changed review the logs, it looks like the notification not pass validation. Attach the logs to the issue.

Regards.
