### ISSUE TITLE
Order Confirmation is sent even if payment is not completed

### ISSUE THREAD

**Issue by JDavidVR** [Codeko/magento2-redsys#14]
Hi!

When I start the payment proccess, module is sending confirmation email. And it must be working like paypal, with pending payment status and send email once  payment is confirmed.

**Comment by boris-burgos** [comment]
Hi JDavidVR.
The module does not send any email, Magento do it. This module only manages the payment status not when or how emails are sent. So this issue is not related to the redsys module.
Regards.
