### ISSUE TITLE
No idea how to implement it

### ISSUE THREAD

**Issue by axeforeverjumo** [Codeko/magento2-redsys#3]
I have a web shop in html, and I want to add A BBVA Bank payment method, this is mazing, but I hace not idea how to do it, I install componser, php, but what i need to do?... :( Please help

**Comment by boris-burgos** [comment]
Hi @axeforeverjumo.

Sorry but this is not a support channel. If you need support please contact codeko@codeko.com and we will send you a quote.

Best regards.
