### ISSUE TITLE
The function mcrypt_encrypt is deprecated in PHP7.1

### ISSUE THREAD

**Issue by rafaelcalero** [Codeko/magento2-redsys#4]
The function mcrypt_encrypt is deprecated in PHP7.1.

1 exception(s):
Exception #0 (Exception): Deprecated Functionality: Function mcrypt_encrypt() is deprecated in /var/www/vhosts/xx/xx/vendor/codeko/magento2-redsys/Helper/Utilities.php on line 54

**Comment by shakaran** [comment]
@boris-burgos this PR should be closed since already merged in master and fixed? Thanks
