### ISSUE TITLE
Error recieving Notification

### ISSUE THREAD

**Issue by Julen10** [Codeko/magento2-redsys#9]
I´m using this module with test environment. When I finished the payment, I´m redirected to Success Page, I recieved the confirmation email but the order is not processed. Checking logs I get this messages:

[2019-03-25 11:14:32] codeko_redsys.INFO: Esperando Notificación ..... [] []
[2019-03-25 11:15:04] codeko_redsys.INFO: Success: Entrada [] []
[2019-03-25 11:15:04] codeko_redsys.INFO: Success: Redsys Without Response:  [] []

Is like Redsys is not sending or module is not recieving POST variables.

**Comment by boris-burgos** [comment]
Hi.
This is not the right place to ask for installation issues or environment issues.
We can't check this issue without check your environment and/or configuration and it is out of this issue system.
If you can report a reproducible and specific bug the issue will be very welcome.

Closed.
